# Generated by Django 4.0.6 on 2022-07-12 03:26

import cars_and_brands.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField(validators=[cars_and_brands.models.car_year_validator])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_and_brands.brand')),
            ],
        ),
    ]
